#@data/values
---
name: grpc-template
service:
  name: grpc-template
  enabled: true
  type: ClusterIP
  ports:
    - name: grpc
      port: 50054
    - name: prometheus
      port: 2112
docker:
  image: grpc-template
  version: latest
env:
  - name: GRPC_SRV_ADDR
    value: localhost:50052
  - name: DB_USER
    value: postgres
  - name: DB_PASS
    value: postgres
  - name: DB_NAME
    value: testdb
  - name: DB_HOST
    value: db
  - name: DB_PORT
    value: 5432
  - name: prometheus_port
    value: 2112
