settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: grpc-template
    path: .
    env:
      GRPC_SRV_ADDR: localhost:50052
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: testdb
      DB_HOST: db
      DB_PORT: 5432
      prometheus_port: 2112
    commands:
      install:
        status: true
        method: go build -o build main.go
      run:
        status: true
        method: ./build
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
