version: '3.1'
services:
  web:
    build: .
    image: grpc-template
    restart: always
    ports:
      - 50052:50052
      - 2112:2112
    links:
      - db
    environment:
      - GRPC_SRV_ADDR=:50052
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=testdb
      - DB_HOST=db
      - DB_PORT=5432
      - prometheus_port=2112
  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
    - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
