create table if not exists employees (id int GENERATED BY DEFAULT AS IDENTITY primary key,	name varchar(30) not null, dept varchar(10) not null, skills varchar(100));

insert into employees (name, dept, skills) values('Test-Emp', 'BE', 'Python, Go');